name: Deploy Next.js to VPS

on:
  push:
    branches:
      - master # deploy when pushing to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the latest code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup SSH access to VPS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # 3️⃣ Deploy to VPS
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          
          echo "🚀 Starting deployment on VPS..."

          # Ensure NVM/Node is available
          export NVM_DIR="\$HOME/.nvm"
          [ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"
          [ -s "\$NVM_DIR/bash_completion" ] && . "\$NVM_DIR/bash_completion"

          # Navigate to project folder (clone if missing)
          if [ ! -d ~/web/yongshi-nirman-sewa ]; then
            mkdir -p ~/web && cd ~/web
            git clone git@github.com:satri-tech/yongshi-nirman-sewa.git
          fi

          cd ~/web/yongshi-nirman-sewa

          echo "📥 Pulling latest code..."
          git fetch --all
          git reset --hard origin/master

          echo "📦 Installing dependencies..."
          npm ci --legacy-peer-deps

          echo "🗄️ Applying database migrations..."
          npx prisma migrate deploy

          echo "⚡ Generating Prisma client..."
          npx prisma generate

          echo "🏗️ Building Next.js app..."
          npm run build

          echo "🔄 Restarting PM2 process..."
          pm2 describe yongshi-app > /dev/null 2>&1 && pm2 restart yongshi-app || pm2 start npm --name "yongshi-app" -- start

          echo "✅ Deployment complete!"
          EOF
