name: Deploy Next.js to VPS

on:
  push:
    branches:
      - master  # deploy when pushing to main branchss hello hiii

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
          
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ~/web/yongshi-nirman-sewa || (cd ~/web && git clone https://github.com/satri-tech/yongshi-nirman-sewa.git && cd yongshi-nirman-sewa)
          git pull origin master
          npm install --legacy-peer-deps
          npx prisma generate
          npm run build
          pm2 stop yongshi-app || true
          pm2 start npm --name "yongshi-app" -- run start
          pm2 save
          EOF
